//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCGMobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesciptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesciptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMCGMobile.Resources.DesciptionResource", typeof(DesciptionResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.1.0.0 Copyright 2018.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time.
        /// </summary>
        internal static string ActiveTime {
            get {
                return ResourceManager.GetString("ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto detect on/off trail status.
        /// </summary>
        internal static string AutoTrack {
            get {
                return ResourceManager.GetString("AutoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you turn off &quot;{0}&quot;, the setting &quot;{1}&quot; will also be turned off.  Fitness can only be tracked when the status is &quot;On Trail&quot;.  You will need to manually turn on/off trail status on the &quot;{2}&quot; page in order to track fitness..
        /// </summary>
        internal static string AutoTrackingInformationalMessage {
            get {
                return ResourceManager.GetString("AutoTrackingInformationalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto detect max distance from trail.
        /// </summary>
        internal static string AutoTrackingMaximumDistanceFromTrail {
            get {
                return ResourceManager.GetString("AutoTrackingMaximumDistanceFromTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average walking speed.
        /// </summary>
        internal static string AverageWalkingSpeed {
            get {
                return ResourceManager.GetString("AverageWalkingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string DaysAbrev {
            get {
                return ResourceManager.GetString("DaysAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display off trail alert to extend on trail status.
        /// </summary>
        internal static string DisplayOffTrailAlert {
            get {
                return ResourceManager.GetString("DisplayOffTrailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Center:.
        /// </summary>
        internal static string DistanceFromTrailCenter {
            get {
                return ResourceManager.GetString("DistanceFromTrailCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected you are {0} from the trail center and the setting &quot;{1}&quot; is turned off. The &quot;On Trail&quot; setting needs to be manually turned on/off on the &quot;{2}&quot; page in order to track fitness. Do you want to turn it off now?.
        /// </summary>
        internal static string FarFromTrailQuestion {
            get {
                return ResourceManager.GetString("FarFromTrailQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string FeetAbrev {
            get {
                return ResourceManager.GetString("FeetAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness History.
        /// </summary>
        internal static string FitnessHistory {
            get {
                return ResourceManager.GetString("FitnessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        internal static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string InchesAbrev {
            get {
                return ResourceManager.GetString("InchesAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0} Longitude: {1}.
        /// </summary>
        internal static string LatitudeLongitude {
            get {
                return ResourceManager.GetString("LatitudeLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbs.
        /// </summary>
        internal static string LbsAbrev {
            get {
                return ResourceManager.GetString("LbsAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        internal static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker List View.
        /// </summary>
        internal static string MarkerListView {
            get {
                return ResourceManager.GetString("MarkerListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string MilesAbrev {
            get {
                return ResourceManager.GetString("MilesAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string MilesPerHour {
            get {
                return ResourceManager.GetString("MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string MinutesAbrev {
            get {
                return ResourceManager.GetString("MinutesAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes to extend on trail status.
        /// </summary>
        internal static string MinutesToExtendOnTrailStatus {
            get {
                return ResourceManager.GetString("MinutesToExtendOnTrailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding for this project was provided by a “Meet Me at the Park” grant from the National Recreation and Park Association and Disney. Grants from this program are providing families with access to play spaces and inspiring kids and families to get active in local communities across the country..
        /// </summary>
        internal static string MMATPFunding {
            get {
                return ResourceManager.GetString("MMATPFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Hyperlinks.
        /// </summary>
        internal static string MobileAppHyperlinks {
            get {
                return ResourceManager.GetString("MobileAppHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string MphAbrev {
            get {
                return ResourceManager.GetString("MphAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of fitness history sessions to keep.
        /// </summary>
        internal static string NumFitnessHistorySessionsToKeep {
            get {
                return ResourceManager.GetString("NumFitnessHistorySessionsToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Trail.
        /// </summary>
        internal static string OffTrail {
            get {
                return ResourceManager.GetString("OffTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your status is changing to &quot;Off Trail&quot;. Do you want to extend the &quot;On Trail&quot; status by {0} mins in order to keep tracking your fitness?.
        /// </summary>
        internal static string OffTrailQuestion {
            get {
                return ResourceManager.GetString("OffTrailQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Trail.
        /// </summary>
        internal static string OnTrail {
            get {
                return ResourceManager.GetString("OnTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIR:.
        /// </summary>
        internal static string OnTrailDirection {
            get {
                return ResourceManager.GetString("OnTrailDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIST:.
        /// </summary>
        internal static string OnTrailDistance {
            get {
                return ResourceManager.GetString("OnTrailDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA:.
        /// </summary>
        internal static string OnTrailETA {
            get {
                return ResourceManager.GetString("OnTrailETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next:.
        /// </summary>
        internal static string OnTrailNextPin {
            get {
                return ResourceManager.GetString("OnTrailNextPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected you are {0} from the trail center and the setting &quot;{1}&quot; is turned off. The &quot;On Trail&quot; setting needs to be manually turned on/off on the &quot;{2}&quot; page in order to track fitness. Do you want to turn it on now?.
        /// </summary>
        internal static string OnTrailQuestion {
            get {
                return ResourceManager.GetString("OnTrailQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        internal static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        internal static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sessn.
        /// </summary>
        internal static string SessionsAbrev {
            get {
                return ResourceManager.GetString("SessionsAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show markers on fitness map.
        /// </summary>
        internal static string ShowMarkersOnFitnessMap {
            get {
                return ResourceManager.GetString("ShowMarkersOnFitnessMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusInfoStatus {
            get {
                return ResourceManager.GetString("StatusInfoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%h} hrs {0:%m} mins.
        /// </summary>
        internal static string TimeSpanDisplay {
            get {
                return ResourceManager.GetString("TimeSpanDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s On Trail Fitness Tracking.
        /// </summary>
        internal static string TodayFitnessTracking {
            get {
                return ResourceManager.GetString("TodayFitnessTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        internal static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
    }
}
